results_base_dir: main/mainTrainingData # Path to the directory where output files are saved.

model_structure:  # Surrogate model Neural Network model structure;
  type: "ESN"
  D_in: 7
  D_out: 1
  input_features: 7
  input_scaling: 0.1
  units: 500
  sequence_length: 200
  sparsity: 0.1
  spectral_radius: 0.1
  ridge: 0.0029801797509298408
  input_scaling: 1.0
  learning_rate: 0.01 # The smaller the learning rate the longer time for the model to be trained

hyperparameters: # Neural Network Hyperparameters for training phase;
  epochs: 15 # Number of tries on the total training dataset;
  # Note: The higher the more accurate model on "Training" dataset
  # Note: Should be chosen appropriately to prevent "Overfitting"


data:
  dataset_paths:
    ["main/mainSamplingData/postprocessed_data.npz"]
    # Paths to the sampled data, which should be either gathered in training, validation, and testing data or splitted later with split_percentages
 

  steps: 1
  batch_size: 5000
  worker_no: 0
  pin_memory: False

  split_percentages: # Default config. where you have collected seperated data for training, validation, and testing data in seperate measurements. # Only works if there is a single dataset path
    - 0.8 # Training data
    - 0.1
    - 0.1 # Dev/validation data
