results_base_dir: main/mainTrainingData # Path to the directory where output files are saved.

model_structure:  # Surrogate model Neural Network model structure;
  type: "RNN"
  input_features: 7
  sequence_length: 100
  hidden_size: 32
  num_layers: 1
  D_in: 7
  D_out: 1

hyperparameters: # Neural Network Hyperparameters for training phase;
  epochs: 30 # Number of tries on the total training dataset;
  # Note: The higher the more accurate model on "Training" dataset
  # Note: Should be chosen appropriately to prevent "Overfitting"
  learning_rate: 0.008 # The smaller the learning rate the longer time for the model to be trained

data:
  dataset_paths:
    ["main/mainSamplingData/postprocessed_data.npz"]
    # Paths to the sampled data, which should be either gathered in training, validation, and testing data or splitted later with split_percentages
 

  steps: 1
  batch_size: 100
  worker_no: 0
  pin_memory: False

  split_percentages: # Default config. where you have collected seperated data for training, validation, and testing data in seperate measurements. # Only works if there is a single dataset path
    - 0.8 # Training data
    - 0.1
    - 0.1 # Dev/validation data
