results_base_dir: "main/mainTrainingData_HyperTuning/LSTM"  # Base directory for saving results
config_base_dir: "configs/training/Tuning/LSTM"  # Base directory for saving generated config files

model_structure:  # Surrogate model Neural Network model structure
  type: "RNN"  # Type of model (e.g., RNN, DNN)
  input_features: 7  # Number of input features
  sequence_length: 100  # Length of the input sequence (this can be varied in the hyperparameter range)
  hidden_size: 32  # Size of the hidden layer (this can be varied in the hyperparameter range)
  num_layers: 1  # Number of layers (this can be varied in the hyperparameter range)
  D_in: 7  # Dimension of input
  D_out: 1  # Dimension of output

hyperparameters:  # Neural Network Hyperparameters for training phase
  epochs: 1  # Number of epochs for training
  learning_rate: 0.01  # Learning rate (this can be varied in the hyperparameter range)

data:  # Data configuration
  dataset_paths:
    - "main/mainSamplingData/postprocessed_data.npz"  # Paths to the dataset
  steps: 1  # Steps to be used during data loading
  batch_size: 100  # Batch size (this can be varied in the hyperparameter range)
  worker_no: 0  # Number of workers for data loading
  pin_memory: False  # Pin memory during data loading
  split_percentages:  # Split percentages for training, validation, and test sets
    - 0.8
    - 0.1
    - 0.1

hyperparameter_ranges:  # Ranges and steps for hyperparameters
  model_structure.sequence_length:  # Range for sequence length
    start: 90
    stop: 101
    step: 10
  model_structure.hidden_size:  # Range for hidden size
    start: 32
    stop: 65
    step: 32
  model_structure.num_layers:  # Range for number of layers
    start: 1
    stop: 2
    step: 1
  hyperparameters.learning_rate:  # Range for learning rate
    values: [0.01]
  data.batch_size:  # Range for batch size
    start: 100
    stop: 201
    step: 100
