results_base_dir: "main/mainTrainingData_HyperTuning/GRU_withRestTime_Layer2"  # Base directory for saving results
config_base_dir: "configs/training/Tuning/GRU_withRestTime_Layer2"  # Base directory for saving generated config files

model_structure:  # Surrogate model Neural Network model structure
  type: "RNN"
  input_features: 7
  sequence_length: 150
  hidden_size: 32
  num_layers: 2
  output_size: 1
  D_in: 7
  D_out: 1
  dropout: 1
  bidirectional: False

hyperparameters:  # Neural Network Hyperparameters for training phase
  epochs: 15  # Number of epochs for training
  learning_rate: 0.01  # Learning rate (this can be varied in the hyperparameter range)

data:  # Data configuration
  dataset_paths:
    - "main/mainSamplingData/postprocessed_data.npz"  # Paths to the dataset
  steps: 1  # Steps to be used during data loading
  batch_size: 5000  # Batch size (this can be varied in the hyperparameter range)
  worker_no: 0  # Number of workers for data loading
  pin_memory: False  # Pin memory during data loading
  split_percentages:  # Split percentages for training, validation, and test sets
    - 0.8
    - 0.1
    - 0.1

hyperparameter_ranges:  # Ranges and steps for hyperparameters
  model_structure.sequence_length:  # Range for sequence length
    start: 50
    stop: 201
    step: 150
  model_structure.hidden_size:  # Range for hidden size
    start: 32
    stop: 289
    step: 64
  model_structure.num_layers:  # Range for number of layers
    start: 2
    stop: 3
    step: 1
  hyperparameters.learning_rate:  # Range for learning rate
    values: [0.01, 0.008]
  data.batch_size:  # Range for batch size
    start: 5000
    stop: 5001
    step: 1
